apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: edgeclass1
  name: 75-edgeclass1
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
      - contents: |
          [Unit]
          Description=check and replace default kernel
          After=kubelet.target
          Before=kublet.service
          After=rpm-ostreed.service
          After=network-online.target

          [Service]
          Type=simple
          ExecStart=/etc/openshiftcustomkerneld/openshiftcustomkernel.sh
          TimeoutStartSec=600
          
          [Install]
          WantedBy=multi-user.target
        enabled: true
        name: openshiftcustomkernel.service