apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: edgeclass1
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [edgeclass1,worker]}
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/edgeclass1: ""